version: '3'

services:

  web:
    image: nginx:1.13.9
    ports:
        - '1001:80'
    volumes:
        - '.:/var/www/html/sf-with-docker/public/'
        - './docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf'
        - './var/logs/nginx/:/var/log/nginx'
    depends_on:
      - php

  php:
    build: docker/php
    volumes:
      - '.:/var/www/html/sf-with-docker'
    ports:
      - '9000:9000'
    depends_on:
      - mydockersql

  mydockersql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: symfony

  tools:
    build: docker/tools
    volumes:
      - ./:/var/www/html/sf-with-docker/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions

